### ISSUE TITLE
sui_pre_draw() and sui_draw() undocumented

### ISSUE THREAD

**Issue by hemebond** [shpuld/sui-qc#1]
`CSQC_UpdateView` has commented-out references to `sui_pre_draw` and `sui_draw` but these functions do not exist. It's unclear to be if the user is supposed to create them.

`sui_action_element` will throw an error if these functions are not called.

It appears `sui_pre_draw` was renamed to `sui_begin`, which sets the variables the rest of the SUI system is checking.

**Comment by shpuld** [comment]
I'll fix this over the weekend, thank you

**Comment by shpuld** [comment]
Better late than never, changed the commented areas to `sui_begin` and `sui_end` as they should be.
