### ISSUE TITLE
Key binding fails when using FTEQW-SDL2

### ISSUE THREAD

**Issue by hemebond** [shpuld/sui-qc#2]
When using fteqw-sdl2 key press events are sent twice; the first time `chary` contains the keycode, the second time `scanx` contains the keycode. This means key binding fails because sui-qc only uses the `scanx` value.

I worked around this by updating `sui_input_event()` with:
```
	case IE_KEYUP:
		if (_sui_binding_command != "")
		{
			local float keycode = (scanx != 0) ? scanx : chary;
			_sui_do_keybind(keycode, _sui_binding_command);
			return TRUE;
		}
```

**Comment by shpuld** [comment]
no downside to this? I can do this change upstream or merge a pr if so

**Comment by hemebond** [comment]
I've JUST tested in the latest versions of fteqw64 and fteqw-sdl2 and I can't replicate the original problem so it must have been a bug in fteqw-sdl2 itself. I'll re-open if I can replicate it.
